id: P000039
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཆོས་མངོན་པ་རྣམ་པར་འབྱེད་པ་ཞེས་བྱ་བའི་བསྟན་བཅོས་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  id: KS-PK-03
web_metadata:
  title:
    en: An Analysis of the Abhidharma
    bo: ཆོས་མངོན་པ་རྣམ་པར་འབྱེད་པ་ཞེས་བྱ་བའི་བསྟན་བཅོས་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 3
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༣
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-03
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-03.epub
  description:
    en: ''
    bo: ''
